version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 2
  target-branch: dependabot-update
  reviewers:
  - Yankovsky
  - ArtyomResh
  ignore:
  - dependency-name: i18next
    versions:
    - ">= 19.a, < 20"
