name: Lighthouse CI check

on:
  deployment_status

jobs:
  run:
    name: Lighthouse CI check
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Download repository with all commits
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Debug payload
        shell: bash
        run: cat $GITHUB_EVENT_PATH
      - name: Extract payload
        id: extract_branch
        run: echo '::set-output name=branch::${{fromJson(github.event.deployment.payload).branch}}'
      - name: Set branch environment variable
        run: echo "GITHUB_BRANCH=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV
      - uses: docker://quay.csssr.cloud/csssr/github-info:v2
        id: gh
      - name: Run Lighthouse for provided urls
        run: npx @lhci/cli@0.4.x autorun --collect.url=https://${{ steps.gh.outputs.releaseID }}.com.csssr.cloud/en
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: https://${{ steps.gh.outputs.releaseID }}.com.csssr.cloud
